---
title: "annotationHeatmaps"
author: "Tara Eicher"
date: "September 10, 2017"
output: html_document
---
Read in the files containing the annotation counts.
```{r setup, include=FALSE}
A549_0 = data.matrix(read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\DNase-seq\\A549_18_annotation_counts\\counts0.csv", header = FALSE))
A549_0_colCounts = colSums(A549_0)
A549_0_rowCounts = rowSums(A549_0)
A549_0 = sweep(A549_0, 2, colSums(A549_0), FUN="/")
A549_1 = data.matrix(read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\DNase-seq\\A549_18_annotation_counts\\counts1.csv", header = FALSE))
A549_1_colCounts = colSums(A549_1)
A549_1_rowCounts = rowSums(A549_1)
A549_1 = sweep(A549_1, 2, colSums(A549_1), FUN="/")
A549_2 = data.matrix(read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\DNase-seq\\A549_18_annotation_counts\\counts2.csv", header = FALSE))
A549_2_colCounts = colSums(A549_2)
A549_2_rowCounts = rowSums(A549_2)
A549_2 = sweep(A549_2, 2, colSums(A549_2), FUN="/")
A549_3 = data.matrix(read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\DNase-seq\\A549_18_annotation_counts\\counts3.csv", header = FALSE))
A549_3_colCounts = colSums(A549_3)
A549_3_rowCounts = rowSums(A549_3)
A549_3 = sweep(A549_3, 2, colSums(A549_3), FUN="/")
A549_4 = data.matrix(read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\DNase-seq\\A549_18_annotation_counts\\counts4.csv", header = FALSE))
A549_4_colCounts = colSums(A549_4)
A549_4_rowCounts = rowSums(A549_4)
A549_4 = sweep(A549_4, 2, colSums(A549_4), FUN="/")
A549_5 = data.matrix(read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\DNase-seq\\A549_18_annotation_counts\\counts5.csv", header = FALSE))
A549_5_colCounts = colSums(A549_5)
A549_5_rowCounts = rowSums(A549_5)
A549_5 = sweep(A549_5, 2, colSums(A549_5), FUN="/")
A549_6 = data.matrix(read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\DNase-seq\\A549_18_annotation_counts\\counts6.csv", header = FALSE))
A549_6_colCounts = colSums(A549_6)
A549_6_rowCounts = rowSums(A549_6)
A549_6 = sweep(A549_6, 2, colSums(A549_6), FUN="/")
```
Set rownames to Roadmap annotations.
```{r}
names = c("TssA", "TssFlnk", "TssFlnkU", "TssFlnkD", "Tx", "TxWk", "EnhG1", "EnhG2", "EnhA1", "EnhA2", "EnhWk", "ZNF/Rpts", "Het", "TssBiv",	"EnhBiv", "ReprPC", "ReprPCWk", "Quies")
rownames(A549_0) = paste(names, " (", A549_0_rowCounts, ")", sep = "")
colnames(A549_0) = paste(colnames(A549_0), " (", A549_0_colCounts, ")", sep = "")
rownames(A549_1) = paste(names, " (", A549_1_rowCounts, ")", sep = "")
colnames(A549_1) = paste(colnames(A549_1), " (", A549_1_colCounts, ")", sep = "")
rownames(A549_2) = paste(names, " (", A549_2_rowCounts, ")", sep = "")
colnames(A549_2) = paste(colnames(A549_2), " (", A549_2_colCounts, ")", sep = "")
rownames(A549_3) = paste(names, " (", A549_3_rowCounts, ")", sep = "")
colnames(A549_3) = paste(colnames(A549_3), " (", A549_3_colCounts, ")", sep = "")
rownames(A549_4) = paste(names, " (", A549_4_rowCounts, ")", sep = "")
colnames(A549_4) = paste(colnames(A549_4), " (", A549_4_colCounts, ")", sep = "")
rownames(A549_5) = paste(names, " (", A549_5_rowCounts, ")", sep = "")
colnames(A549_5) = paste(colnames(A549_5), " (", A549_5_colCounts, ")", sep = "")
rownames(A549_6) = paste(names, " (", A549_6_rowCounts, ")", sep = "")
colnames(A549_6) = paste(colnames(A549_6), " (", A549_6_colCounts, ")", sep = "")
```

Generate full heat maps for A549.
```{r}
if (!require(gplots)){
  install.packages("gplots")
  library(gplots)
}
heatmap.2(A549_0, Rowv = NA, Colv = NA, xlab = "Cluster", main = "A549 Annotation Counts (500 bp)", col = colorRampPalette(c("white","red"))(256), tracecol = NA, ColSideColors = c("blue", "red", "green", "black", "purple", "brown"), margins = c(10,10), cexCol = 1)
heatmap.2(A549_1, Rowv = NA, Colv = NA, xlab = "Cluster", main = "A549 Annotation Counts (1000 bp)", col = colorRampPalette(c("white","red"))(256), tracecol = NA, ColSideColors = c("blue", "red", "green", "black", "purple", "brown"), margins = c(10,10), cexCol = 1)
heatmap.2(A549_2, Rowv = NA, Colv = NA, xlab = "Cluster", main = "A549 Annotation Counts (2000 bp)", col = colorRampPalette(c("white","red"))(256), tracecol = NA, ColSideColors = c("blue", "red", "green", "black", "purple", "brown"), margins = c(10,10), cexCol = 1)
heatmap.2(A549_3, Rowv = NA, Colv = NA, xlab = "Cluster", main = "A549 Annotation Counts (4000 bp)", col = colorRampPalette(c("white","red"))(256), tracecol = NA, ColSideColors = c("blue", "red", "green", "black", "purple", "brown", "dark green"), margins = c(10,10), cexCol = 1)
heatmap.2(A549_4, Rowv = NA, Colv = NA, xlab = "Cluster", main = "A549 Annotation Counts (8000 bp)", col = colorRampPalette(c("white","red"))(256), tracecol = NA, ColSideColors = c("blue", "red", "green", "black", "purple", "brown", "dark green", "blue", "red", "green", "black", "purple", "brown", "dark green"), margins = c(10,10), cexCol = 1)
heatmap.2(A549_5, Rowv = NA, Colv = NA, xlab = "Cluster", main = "A549 Annotation Counts (16000 bp)", col = colorRampPalette(c("white","red"))(256), tracecol = NA, ColSideColors = c("blue", "red", "green", "black", "purple", "brown", "dark green", "blue", "red", "green", "black", "purple", "brown"), margins = c(10,10), cexCol = 1)
heatmap.2(A549_6, Rowv = NA, Colv = NA, xlab = "Cluster", main = "A549 Annotation Counts (32000 bp)", col = colorRampPalette(c("white","red"))(256), tracecol = NA, ColSideColors = c("blue", "red", "green", "black", "purple", "brown", "dark green", "blue"), margins = c(10,10), cexCol = 1)
```
