---
title: "Centroid Count Distributions"
author: "Tara Eicher"
date: "July 9, 2017"
output: html_document
---

```{r}
centroid_counts0_baseline = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15\\som_centroid_counts0")
centroid_counts0_batch_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_100\\som_centroid_counts0")
centroid_counts0_batch_10000 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_10000\\som_centroid_counts0")
centroid_counts0_cosine = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_cosine\\som_centroid_counts0")
centroid_counts0_manhattan = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_manhattan\\som_centroid_counts0")
centroid_counts0_grid_25 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_25\\som_centroid_counts0")
centroid_counts0_grid_2500 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_2500\\som_centroid_counts0")
centroid_counts0_iter_2 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_2\\som_centroid_counts0")
centroid_counts0_iter_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_100\\som_centroid_counts0")
centroid_counts0_lr_01 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_01\\som_centroid_counts0")
centroid_counts0_lr_09 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_09\\som_centroid_counts0")
centroid_counts0_neigh_1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_1\\som_centroid_counts0")
centroid_counts0_neigh_10 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_10\\som_centroid_counts0")
centroid_counts0_auto_a549 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_a549\\som_centroid_counts0")
centroid_counts0_auto_brain = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_brain\\som_centroid_counts0")
centroid_counts0_auto_h1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_h1\\som_centroid_counts0")
```

```{r}
plot(density(as.numeric(unlist(centroid_counts0_lr_01)) / 10), main="Distribution of Counts by Learning Rate (Window Size 500)", col = "red")
lines(density(as.numeric(unlist(centroid_counts0_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts0_lr_09)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("0.1", "0.3", "0.9"), col= c("red", "blue", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts0_neigh_10)) / 10), main="Distribution of Counts by Neighborhood Size (Window Size 500)", col = "red")
lines(density(as.numeric(unlist(centroid_counts0_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts0_neigh_1)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("1", "5", "10"), col= c("green", "blue", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts0_baseline)) / 10), main="Distribution of Counts by Batch Size (Window Size 500)", col = "red")
lines(density(as.numeric(unlist(centroid_counts0_batch_100)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts0_batch_10000)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("100", "1000", "10000"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts0_baseline)) / 10), main="Distribution of Counts by Iteration Count (Window Size 500)", col = "red")
lines(density(as.numeric(unlist(centroid_counts0_iter_2)) / 2), col = "blue")
lines(density(as.numeric(unlist(centroid_counts0_iter_100)) / 100), col = "green")
legend(x= "topright", y=0.92, legend=c("2", "10", "100"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts0_grid_2500)) / 10), main="Distribution of Counts by Grid Size (Window Size 500)", col = "red")
lines(density(as.numeric(unlist(centroid_counts0_grid_25)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts0_baseline)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("5", "10", "50"), col= c("blue", "green", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts0_baseline)) / 10), main="Distribution of Counts by Distance Metric (Window Size 500)", col = "red")
lines(density(as.numeric(unlist(centroid_counts0_manhattan)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts0_cosine)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("Euclidean", "Manhattan", "Cosine"), col= c("red", "blue", "green"), lwd = 2)
```


```{r}
centroid_counts1_baseline = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15\\som_centroid_counts1")
centroid_counts1_batch_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_100\\som_centroid_counts1")
centroid_counts1_batch_10000 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_10000\\som_centroid_counts1")
centroid_counts1_cosine = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_cosine\\som_centroid_counts1")
centroid_counts1_manhattan = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_manhattan\\som_centroid_counts1")
centroid_counts1_grid_25 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_25\\som_centroid_counts1")
centroid_counts1_grid_2500 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_2500\\som_centroid_counts1")
centroid_counts1_iter_2 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_2\\som_centroid_counts1")
centroid_counts1_iter_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_100\\som_centroid_counts1")
centroid_counts1_lr_01 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_01\\som_centroid_counts1")
centroid_counts1_lr_09 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_09\\som_centroid_counts1")
centroid_counts1_neigh_1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_1\\som_centroid_counts1")
centroid_counts1_neigh_10 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_10\\som_centroid_counts1")
centroid_counts1_auto_a549 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_a549\\som_centroid_counts1")
centroid_counts1_auto_brain = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_brain\\som_centroid_counts1")
centroid_counts1_auto_h1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_h1\\som_centroid_counts1")
```

```{r}
plot(density(as.numeric(unlist(centroid_counts1_lr_01)) / 10), main="Distribution of Counts by Learning Rate (Window Size 1000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts1_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts1_lr_09)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("0.1", "0.3", "0.9"), col= c("red", "blue", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts1_neigh_10)) / 10), main="Distribution of Counts by Neighborhood Size (Window Size 1000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts1_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts1_neigh_1)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("1", "5", "10"), col= c("green", "blue", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts1_batch_10000)) / 10), main="Distribution of Counts by Batch Size (Window Size 1000)", col = "green")
lines(density(as.numeric(unlist(centroid_counts1_batch_100)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts1_baseline)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("100", "1000", "10000"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts1_iter_100)) / 100), main="Distribution of Counts by Iteration Count (Window Size 1000)", col = "green")
lines(density(as.numeric(unlist(centroid_counts1_iter_2)) / 2), col = "blue")
lines(density(as.numeric(unlist(centroid_counts1_baseline)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("2", "10", "100"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts1_grid_2500)) / 10), main="Distribution of Counts by Grid Size (Window Size 1000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts1_grid_25)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts1_baseline)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("5", "10", "50"), col= c("blue", "green", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts1_cosine)) / 10), main="Distribution of Counts by Distance Metric (Window Size 1000)", col = "green")
lines(density(as.numeric(unlist(centroid_counts1_manhattan)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts1_baseline)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("Euclidean", "Manhattan", "Cosine"), col= c("red", "blue", "green"), lwd = 2)
```


```{r}
centroid_counts2_baseline = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15\\som_centroid_counts2")
centroid_counts2_batch_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_100\\som_centroid_counts2")
centroid_counts2_batch_10000 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_10000\\som_centroid_counts2")
centroid_counts2_cosine = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_cosine\\som_centroid_counts2")
centroid_counts2_manhattan = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_manhattan\\som_centroid_counts2")
centroid_counts2_grid_25 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_25\\som_centroid_counts2")
centroid_counts2_grid_2500 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_2500\\som_centroid_counts2")
centroid_counts2_iter_2 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_2\\som_centroid_counts2")
centroid_counts2_iter_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_100\\som_centroid_counts2")
centroid_counts2_lr_01 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_01\\som_centroid_counts2")
centroid_counts2_lr_09 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_09\\som_centroid_counts2")
centroid_counts2_neigh_1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_1\\som_centroid_counts2")
centroid_counts2_neigh_10 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_10\\som_centroid_counts2")
centroid_counts2_auto_a549 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_a549\\som_centroid_counts2")
centroid_counts2_auto_brain = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_brain\\som_centroid_counts2")
centroid_counts2_auto_h1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_h1\\som_centroid_counts2")
```

```{r}
plot(density(as.numeric(unlist(centroid_counts2_lr_01)) / 10), main="Distribution of Counts by Learning Rate (Window Size 2000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts2_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts2_lr_09)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("0.1", "0.3", "0.9"), col= c("red", "blue", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts2_neigh_10)) / 10), main="Distribution of Counts by Neighborhood Size (Window Size 2000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts2_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts2_neigh_1)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("1", "5", "10"), col= c("green", "blue", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts2_batch_10000)) / 10), main="Distribution of Counts by Batch Size (Window Size 2000)", col = "green")
lines(density(as.numeric(unlist(centroid_counts2_batch_100)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts2_baseline)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("100", "1000", "10000"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts2_iter_2)) / 2), main="Distribution of Counts by Iteration Count (Window Size 2000)", col = "blue")
lines(density(as.numeric(unlist(centroid_counts2_iter_100)) / 100), col = "green")
lines(density(as.numeric(unlist(centroid_counts2_baseline)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("2", "10", "100"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts2_grid_2500)) / 10), main="Distribution of Counts by Grid Size (Window Size 2000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts2_grid_25)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts2_baseline)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("5", "10", "50"), col= c("blue", "green", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts2_manhattan)) / 10), main="Distribution of Counts by Distance Metric (Window Size 2000)", col = "blue")
lines(density(as.numeric(unlist(centroid_counts2_baseline)) / 10), col = "red")
lines(density(as.numeric(unlist(centroid_counts2_cosine)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("Euclidean", "Manhattan", "Cosine"), col= c("red", "blue", "green"), lwd = 2)
```


```{r}
centroid_counts3_baseline = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15\\som_centroid_counts3")
centroid_counts3_batch_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_100\\som_centroid_counts3")
centroid_counts3_batch_10000 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_10000\\som_centroid_counts3")
centroid_counts3_cosine = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_cosine\\som_centroid_counts3")
centroid_counts3_manhattan = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_manhattan\\som_centroid_counts3")
centroid_counts3_grid_25 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_25\\som_centroid_counts3")
centroid_counts3_grid_2500 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_2500\\som_centroid_counts3")
centroid_counts3_iter_2 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_2\\som_centroid_counts3")
centroid_counts3_iter_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_100\\som_centroid_counts3")
centroid_counts3_lr_01 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_01\\som_centroid_counts3")
centroid_counts3_lr_09 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_09\\som_centroid_counts3")
centroid_counts3_neigh_1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_1\\som_centroid_counts3")
centroid_counts3_neigh_10 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_10\\som_centroid_counts3")
centroid_counts3_auto_a549 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_a549\\som_centroid_counts3")
centroid_counts3_auto_brain = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_brain\\som_centroid_counts3")
centroid_counts3_auto_h1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_h1\\som_centroid_counts3")
```

```{r}
plot(density(as.numeric(unlist(centroid_counts3_lr_01)) / 10), main="Distribution of Counts by Learning Rate (Window Size 4000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts3_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts3_lr_09)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("0.1", "0.3", "0.9"), col= c("red", "blue", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts3_neigh_1)) / 10), main="Distribution of Counts by Neighborhood Size (Window Size 4000)", col = "green")
lines(density(as.numeric(unlist(centroid_counts3_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts3_neigh_10)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("1", "5", "10"), col= c("green", "blue", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts3_batch_10000)) / 10), main="Distribution of Counts by Batch Size (Window Size 4000)", col = "green")
lines(density(as.numeric(unlist(centroid_counts3_baseline)) / 10), col = "red")
lines(density(as.numeric(unlist(centroid_counts3_batch_100)) / 10), col = "blue")
legend(x= "topright", y=0.92, legend=c("100", "1000", "10000"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts3_iter_2)) / 10), main="Distribution of Counts by Iteration Count (Window Size 4000)", col = "blue")
lines(density(as.numeric(unlist(centroid_counts3_baseline)) / 2), col = "red")
lines(density(as.numeric(unlist(centroid_counts3_iter_100)) / 100), col = "green")
legend(x= "topright", y=0.92, legend=c("2", "10", "100"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts3_grid_2500)) / 10), main="Distribution of Counts by Grid Size (Window Size 4000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts3_grid_25)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts3_baseline)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("5", "10", "50"), col= c("blue", "green", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts3_manhattan)) / 10), main="Distribution of Counts by Distance Metric (Window Size 4000)", col = "blue")
lines(density(as.numeric(unlist(centroid_counts3_baseline)) / 10), col = "red")
lines(density(as.numeric(unlist(centroid_counts3_cosine)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("Euclidean", "Manhattan", "Cosine"), col= c("red", "blue", "green"), lwd = 2)
```


```{r}
centroid_counts4_baseline = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15\\som_centroid_counts4")
centroid_counts4_batch_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_100\\som_centroid_counts4")
centroid_counts4_batch_10000 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_10000\\som_centroid_counts4")
centroid_counts4_cosine = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_cosine\\som_centroid_counts4")
centroid_counts4_manhattan = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_manhattan\\som_centroid_counts4")
centroid_counts4_grid_25 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_25\\som_centroid_counts4")
centroid_counts4_grid_2500 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_2500\\som_centroid_counts4")
centroid_counts4_iter_2 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_2\\som_centroid_counts4")
centroid_counts4_iter_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_100\\som_centroid_counts4")
centroid_counts4_lr_01 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_01\\som_centroid_counts4")
centroid_counts4_lr_09 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_09\\som_centroid_counts4")
centroid_counts4_neigh_1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_1\\som_centroid_counts4")
centroid_counts4_neigh_10 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_10\\som_centroid_counts4")
centroid_counts4_auto_a549 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_a549\\som_centroid_counts4")
centroid_counts4_auto_brain = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_brain\\som_centroid_counts4")
centroid_counts4_auto_h1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_h1\\som_centroid_counts4")
```

```{r}
plot(density(as.numeric(unlist(centroid_counts4_lr_01)) / 10), main="Distribution of Counts by Learning Rate (Window Size 8000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts4_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts4_lr_09)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("0.1", "0.3", "0.9"), col= c("red", "blue", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts4_neigh_10)) / 10), main="Distribution of Counts by Neighborhood Size (Window Size 8000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts4_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts4_neigh_1)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("1", "5", "10"), col= c("green", "blue", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts4_batch_10000)) / 10), main="Distribution of Counts by Batch Size (Window Size 8000)", col = "green")
lines(density(as.numeric(unlist(centroid_counts4_batch_100)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts4_baseline)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("100", "1000", "10000"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts4_iter_2)) / 2), main="Distribution of Counts by Iteration Count (Window Size 8000)", col = "blue")
lines(density(as.numeric(unlist(centroid_counts4_iter_100)) / 100), col = "green")
lines(density(as.numeric(unlist(centroid_counts4_baseline)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("2", "10", "100"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts4_grid_2500)) / 10), main="Distribution of Counts by Grid Size (Window Size 8000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts4_grid_25)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts4_baseline)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("5", "10", "50"), col= c("blue", "green", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts4_manhattan)) / 10), main="Distribution of Counts by Distance Metric (Window Size 8000)", col = "blue")
lines(density(as.numeric(unlist(centroid_counts4_baseline)) / 10), col = "red")
lines(density(as.numeric(unlist(centroid_counts4_cosine)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("Euclidean", "Manhattan", "Cosine"), col= c("red", "blue", "green"), lwd = 2)
```


```{r}
centroid_counts5_baseline = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15\\som_centroid_counts5")
centroid_counts5_batch_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_100\\som_centroid_counts5")
centroid_counts5_batch_10000 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_10000\\som_centroid_counts5")
centroid_counts5_cosine = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_cosine\\som_centroid_counts5")
centroid_counts5_manhattan = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_manhattan\\som_centroid_counts5")
centroid_counts5_grid_25 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_25\\som_centroid_counts5")
centroid_counts5_grid_2500 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_2500\\som_centroid_counts5")
centroid_counts5_iter_2 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_2\\som_centroid_counts5")
centroid_counts5_iter_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_100\\som_centroid_counts5")
centroid_counts5_lr_01 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_01\\som_centroid_counts5")
centroid_counts5_lr_09 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_09\\som_centroid_counts5")
centroid_counts5_neigh_1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_1\\som_centroid_counts5")
centroid_counts5_neigh_10 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_10\\som_centroid_counts5")
centroid_counts5_auto_a549 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_a549\\som_centroid_counts5")
centroid_counts5_auto_brain = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_brain\\som_centroid_counts5")
centroid_counts5_auto_h1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_h1\\som_centroid_counts5")
```

```{r}
plot(density(as.numeric(unlist(centroid_counts5_lr_01)) / 10), main="Distribution of Counts by Learning Rate (Window Size 16000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts5_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts5_lr_09)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("0.1", "0.3", "0.9"), col= c("red", "blue", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts5_neigh_10)) / 10), main="Distribution of Counts by Neighborhood Size (Window Size 16000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts5_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts5_neigh_1)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("1", "5", "10"), col= c("green", "blue", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts5_batch_10000)) / 10), main="Distribution of Counts by Batch Size (Window Size 16000)", col = "green")
lines(density(as.numeric(unlist(centroid_counts5_baseline)) / 10), col = "red")
lines(density(as.numeric(unlist(centroid_counts5_batch_100)) / 10), col = "blue")
legend(x= "topright", y=0.92, legend=c("100", "1000", "10000"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts5_iter_2)) / 2), main="Distribution of Counts by Iteration Count (Window Size 16000)", col = "blue")
lines(density(as.numeric(unlist(centroid_counts5_iter_100)) / 100), col = "green")
lines(density(as.numeric(unlist(centroid_counts5_baseline)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("2", "10", "100"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts5_grid_2500)) / 10), main="Distribution of Counts by Grid Size (Window Size 16000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts5_grid_25)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts5_baseline)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("5", "10", "50"), col= c("blue", "green", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts5_manhattan)) / 10), main="Distribution of Counts by Distance Metric (Window Size 16000)", col = "blue")
lines(density(as.numeric(unlist(centroid_counts5_baseline)) / 10), col = "red")
lines(density(as.numeric(unlist(centroid_counts5_cosine)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("Euclidean", "Manhattan", "Cosine"), col= c("red", "blue", "green"), lwd = 2)
```


```{r}
centroid_counts6_baseline = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15\\som_centroid_counts6")
centroid_counts6_batch_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_100\\som_centroid_counts6")
centroid_counts6_batch_10000 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_batch_10000\\som_centroid_counts6")
centroid_counts6_cosine = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_cosine\\som_centroid_counts6")
centroid_counts6_manhattan = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_manhattan\\som_centroid_counts6")
centroid_counts6_grid_25 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_25\\som_centroid_counts6")
centroid_counts6_grid_2500 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_grid_2500\\som_centroid_counts6")
centroid_counts6_iter_2 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_2\\som_centroid_counts6")
centroid_counts6_iter_100 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_iter_100\\som_centroid_counts6")
centroid_counts6_lr_01 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_01\\som_centroid_counts6")
centroid_counts6_lr_09 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_lr_09\\som_centroid_counts6")
centroid_counts6_neigh_1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_1\\som_centroid_counts6")
centroid_counts6_neigh_10 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_neigh_10\\som_centroid_counts6")
centroid_counts6_auto_a549 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_a549\\som_centroid_counts6")
centroid_counts6_auto_brain = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_brain\\som_centroid_counts6")
centroid_counts6_auto_h1 = read.csv("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\chrom15_auto_h1\\som_centroid_counts6")
```

```{r}
plot(density(as.numeric(unlist(centroid_counts6_lr_01)) / 10), main="Distribution of Counts by Learning Rate (Window Size 32000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts6_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts6_lr_09)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("0.1", "0.3", "0.9"), col= c("red", "blue", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts6_neigh_10)) / 10), main="Distribution of Counts by Neighborhood Size (Window Size 32000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts6_baseline)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts6_neigh_1)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("1", "5", "10"), col= c("green", "blue", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts6_batch_10000)) / 10), main="Distribution of Counts by Batch Size (Window Size 32000)", col = "green")
lines(density(as.numeric(unlist(centroid_counts6_batch_100)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts6_baseline)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("100", "1000", "10000"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts6_iter_2) / 2)), main="Distribution of Counts by Iteration Count (Window Size 32000)", col = "blue")
lines(density(as.numeric(unlist(centroid_counts6_iter_100)) / 100), col = "green")
lines(density(as.numeric(unlist(centroid_counts6_baseline)) / 10), col = "red")
legend(x= "topright", y=0.92, legend=c("2", "10", "100"), col= c("blue", "red", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts6_grid_2500)) / 10), main="Distribution of Counts by Grid Size (Window Size 32000)", col = "red")
lines(density(as.numeric(unlist(centroid_counts6_grid_25)) / 10), col = "blue")
lines(density(as.numeric(unlist(centroid_counts6_baseline)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("5", "10", "50"), col= c("blue", "green", "red"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts6_manhattan)) / 10), main="Distribution of Counts by Distance Metric (Window Size 32000)", col = "blue")
lines(density(as.numeric(unlist(centroid_counts6_baseline)) / 10), col = "red")
lines(density(as.numeric(unlist(centroid_counts6_cosine)) / 10), col = "green")
legend(x= "topright", y=0.92, legend=c("Euclidean", "Manhattan", "Cosine"), col= c("red", "blue", "green"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts6_auto_a549))), main="Distribution of Counts for Automatic Parameter Selection - A549", col = "purple")
lines(density(as.numeric(unlist(centroid_counts5_auto_a549))), col = "black")
lines(density(as.numeric(unlist(centroid_counts4_auto_a549))), col = "blue")
lines(density(as.numeric(unlist(centroid_counts3_auto_a549))), col = "green")
lines(density(as.numeric(unlist(centroid_counts2_auto_a549))), col = "brown")
lines(density(as.numeric(unlist(centroid_counts1_auto_a549))), col = "orange")
lines(density(as.numeric(unlist(centroid_counts0_auto_a549))), col = "red")
legend(x= "topright", y=0.92, legend=c("500 bp", "1000 bp", "2000 bp", "4000 bp", "8000 bp", "16000 bp", "32000 bp"), col= c("red", "orange", "brown", "green", "blue", "black", "purple"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts6_auto_brain))), main="Distribution of Counts for Automatic Parameter Selection - Brain", col = "purple")
lines(density(as.numeric(unlist(centroid_counts5_auto_brain))), col = "black")
lines(density(as.numeric(unlist(centroid_counts4_auto_brain))), col = "blue")
lines(density(as.numeric(unlist(centroid_counts3_auto_brain))), col = "green")
lines(density(as.numeric(unlist(centroid_counts2_auto_brain))), col = "brown")
lines(density(as.numeric(unlist(centroid_counts1_auto_brain))), col = "orange")
lines(density(as.numeric(unlist(centroid_counts0_auto_brain))), col = "red")
legend(x= "topright", y=0.92, legend=c("500 bp", "1000 bp", "2000 bp", "4000 bp", "8000 bp", "16000 bp", "32000 bp"), col= c("red", "orange", "brown", "green", "blue", "black", "purple"), lwd = 2)
```

```{r}
plot(density(as.numeric(unlist(centroid_counts6_auto_h1))), main="Distribution of Counts for Automatic Parameter Selection - H1", col = "purple")
lines(density(as.numeric(unlist(centroid_counts5_auto_h1))), col = "black")
lines(density(as.numeric(unlist(centroid_counts4_auto_h1))), col = "blue")
lines(density(as.numeric(unlist(centroid_counts3_auto_h1))), col = "green")
lines(density(as.numeric(unlist(centroid_counts2_auto_h1))), col = "brown")
lines(density(as.numeric(unlist(centroid_counts1_auto_h1))), col = "orange")
lines(density(as.numeric(unlist(centroid_counts0_auto_h1))), col = "red")
legend(x= "topright", y=0.92, legend=c("500 bp", "1000 bp", "2000 bp", "4000 bp", "8000 bp", "16000 bp", "32000 bp"), col= c("red", "orange", "brown", "green", "blue", "black", "purple"), lwd = 2)
```