---
title: "Plot_Cluster_Counts"
author: "Tara Eicher"
date: "September 23, 2017"
output: html_document
---

```{r}
plot(x = c(500, 1000, 2000, 4000, 8000, 16000, 32000), y = c(6, 10, 9, 14, 16, 29, 115), ylim = c(0, 150), main = "Number of Clusters per Window Size", xlab = "Window Size (in bp)", ylab = "Cluster Count", type = "n")
lines(x = c(500, 1000, 2000, 4000, 8000, 16000, 32000), y = c(6, 10, 9, 14, 16, 29, 115), type = "o", col = "magenta")
lines(x = c(500, 1000, 2000, 4000, 8000, 16000, 32000), y = c(2, 7, 2, 8, 8, 28, 43), type = "o", col = "blue")
lines(x = c(500, 1000, 2000, 4000, 8000, 16000, 32000), y = c(5, 7, 7, 9, 7, 23, 104), type = "o", col = "brown")
```
```{r fig.height = 10, fig.width = 15}
names_15_states = c("TssA", "TssAFlnk", "TxFlnk", "Tx", "TxWk", "EnhG", "Enh", "ZNF/Rpts", "Het", "TssBiv", "BivFlnk", "EnhBiv", "ReprPC", "ReprPCWk", "Quies")
#colors_15 = c("red", "orange", "yellow", "green", "blue", "purple", "magenta", "black", "brown", "gray", "dark blue", "dark green", "dark red", "light blue", "pink")
E003_15_lists = readLines("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\DNase-seq\\ChromHMM_density\\E003_region_sizes.csv")
E003_15_data = list()
for(i in 1:length(names_15_states)){
  E003_15_data[[i]] = as.list(as.numeric(strsplit(E003_15_lists, ",")[[i]]))
}
par(mfrow = c(4, 4))
for(i in 1:length(names_15_states)){
  plot(density(as.numeric(E003_15_data[[i]])), main = paste("ChromHMM Annotation Size (H1) - ", names_15_states[i]))
}
```
```{r fig.height = 10, fig.width = 15}
E081_15_lists = readLines("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\DNase-seq\\ChromHMM_density\\E081_region_sizes.csv")
E081_15_data = list()
for(i in 1:length(names_15_states)){
  E081_15_data[[i]] = as.list(as.numeric(strsplit(E081_15_lists, ",")[[i]]))
}

par(mfrow = c(4, 4))
for(i in 1:length(names_15_states)){
  plot(density(as.numeric(E081_15_data[[i]])), main = paste("ChromHMM Annotation Size (Brain) - ", names_15_states[i]))
}
```

```{r fig.height = 10, fig.width = 15}
E114_15_lists = readLines("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\DNase-seq\\ChromHMM_density\\E114_region_sizes.csv")
E114_15_data = list()
for(i in 1:length(names_15_states)){
  E114_15_data[[i]] = as.list(as.numeric(strsplit(E114_15_lists, ",")[[i]]))
}

par(mfrow = c(4, 4))
for(i in 1:length(names_15_states)){
  plot(density(as.numeric(E114_15_data[[i]])), main = paste("ChromHMM Annotation Size (A549) - ", names_15_states[i]))
}
```