---
title: "MetaStatistics"
author: "Tara Eicher"
date: "March 31, 2017"
output: html_document
---

Load all data.
```{r}
chroms = c(as.character(seq(1,22)), "x", "y")
chroms_non = c(as.character(c(5, 10)))
fseqH1StatList = vector("list", 24)
fseqH1NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\H1_fseq10_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  fseqH1StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\H1_fseq_non_csvs\\peakStatschr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    fseqH1NonStatList[[ind]] = tempNonFrame
  }
}
fseqH1AllPeaks = do.call("rbind", fseqH1StatList[1:24])
fseqH1AllNonPeaks = do.call("rbind", fseqH1NonStatList[1:2])
```

```{r}
macs2_broadH1StatList = vector("list", 24)
macs2_broadH1NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\H1_macs2_broad_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_broadH1StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\H1_macs2_broad_non_csvs\\PeakStatschr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    macs2_broadH1NonStatList[[ind]] = tempNonFrame
  }
}
macs2_broadH1AllPeaks = do.call("rbind", macs2_broadH1StatList[1:24])
macs2_broadH1AllNonPeaks = do.call("rbind", macs2_broadH1NonStatList[1:2])
```

```{r}
macs2_narrowH1StatList = vector("list", 24)
macs2_narrowH1NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\H1_macs2_narrow_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_narrowH1StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\H1_macs2_narrow_non_csvs\\peakStatschr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    macs2_narrowH1NonStatList[[ind]] = tempNonFrame
  }
}
macs2_narrowH1AllPeaks = do.call("rbind", macs2_narrowH1StatList[1:24])
macs2_narrowH1AllNonPeaks = do.call("rbind", macs2_narrowH1NonStatList[1:2])
```

```{r}
peakdeckH1StatList = vector("list", 24)
peakdeckH1NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\H1_peakdeck_csvs\\peakStatschr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  peakdeckH1StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\H1_peakdeck_non_csvs\\peakStatschr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    peakdeckH1NonStatList[[ind]] = tempNonFrame
  }
}
peakdeckH1AllPeaks = do.call("rbind", peakdeckH1StatList[1:24])
peakdeckH1AllNonPeaks = do.call("rbind", peakdeckH1NonStatList[1:2])
```
Look at histogram of each statistic (non-peak).
```{r}
plot(density(fseqH1AllPeaks$Size), main="Distribution of Peak Size", xlab="Peak Size (in increments of 50)", xlim = c(0,150), col = "green")
lines(density(macs2_broadH1AllPeaks$Size), col = "magenta")
lines(density(macs2_narrowH1AllPeaks$Size), col = "blue")
lines(density(peakdeckH1AllPeaks$Size), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqH1AllNonPeaks$Size), main="Distribution of Peak Size", xlab="Peak Size (in increments of 50)", xlim = c(0,50), col = "green")
lines(density(macs2_broadH1AllNonPeaks$Size), col = "magenta")
lines(density(macs2_narrowH1AllNonPeaks$Size), col = "blue")
lines(density(peakdeckH1AllNonPeaks$Size), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(fseqH1AllPeaks$Min), main="Distribution of Peak Min", xlab="Peak Min", xlim = c(0,10), col = "green")
lines(density(macs2_broadH1AllPeaks$Min), col = "magenta")
lines(density(macs2_narrowH1AllPeaks$Min), col = "blue")
lines(density(peakdeckH1AllPeaks$Min), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqH1AllNonPeaks$Min), main="Distribution of Peak Min", xlab="Peak Min)", xlim = c(0,10), col = "green")
lines(density(macs2_broadH1AllNonPeaks$Min), col = "magenta")
lines(density(macs2_narrowH1AllNonPeaks$Min), col = "blue")
lines(density(peakdeckH1AllNonPeaks$Min), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(fseqH1AllPeaks$Max), main="Distribution of Peak Max", xlab="Peak Max", xlim = c(0,40), col = "green")
lines(density(macs2_broadH1AllPeaks$Max), col = "magenta")
lines(density(macs2_narrowH1AllPeaks$Max), col = "blue")
lines(density(peakdeckH1AllPeaks$Max), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqH1AllNonPeaks$Max), main="Distribution of Non-Peak Max", xlab="Peak Max)", xlim = c(0,40), col = "green")
lines(density(macs2_broadH1AllNonPeaks$Max), col = "magenta")
lines(density(macs2_narrowH1AllNonPeaks$Max), col = "blue")
lines(density(peakdeckH1AllNonPeaks$Max), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(fseqH1AllPeaks$Mean), main="Distribution of Peak Mean", xlab="Peak Mean", xlim = c(0,40), col = "green")
lines(density(macs2_broadH1AllPeaks$Mean), col = "magenta")
lines(density(macs2_narrowH1AllPeaks$Mean), col = "blue")
lines(density(peakdeckH1AllPeaks$Mean), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqH1AllNonPeaks$Mean), main="Distribution of Non-Peak Mean", xlab="Peak Mean)", xlim = c(0,40), col = "green")
lines(density(macs2_broadH1AllNonPeaks$Mean), col = "magenta")
lines(density(macs2_narrowH1AllNonPeaks$Mean), col = "blue")
lines(density(peakdeckH1AllNonPeaks$Mean), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqH1AllPeaks$Variance)), main="Distribution of Peak Variance", xlab="Peak Variance", xlim = c(0,40), col = "green")
lines(density(na.omit(macs2_broadH1AllPeaks$Variance)), col = "magenta")
lines(density(na.omit(macs2_narrowH1AllPeaks$Variance)), col = "blue")
lines(density(na.omit(peakdeckH1AllPeaks$Variance)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqH1AllNonPeaks$Variance)), main="Distribution of Non-Peak Variance", xlab="Peak Variance", xlim = c(0,40), col = "green")
lines(density(na.omit(macs2_broadH1AllNonPeaks$Variance)), col = "magenta")
lines(density(na.omit(macs2_narrowH1AllNonPeaks$Variance)), col = "blue")
lines(density(na.omit(peakdeckH1AllNonPeaks$Variance)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqH1AllPeaks$Skewness)), main="Distribution of Peak Skewness", xlab="Peak Skewness", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadH1AllPeaks$Skewness)), col = "magenta")
lines(density(na.omit(macs2_narrowH1AllPeaks$Skewness)), col = "blue")
lines(density(na.omit(peakdeckH1AllPeaks$Skewness)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqH1AllNonPeaks$Skewness)), main="Distribution of Non-Peak Skewness", xlab="Peak Skewness", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadH1AllNonPeaks$Skewness)), col = "magenta")
lines(density(na.omit(macs2_narrowH1AllNonPeaks$Skewness)), col = "blue")
lines(density(na.omit(peakdeckH1AllNonPeaks$Skewness)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqH1AllPeaks$Kurtosis)), main="Distribution of Peak Kurtosis", xlab="Peak Kurtosis", xlim = c(-5,15), col = "green")
lines(density(na.omit(macs2_broadH1AllPeaks$Kurtosis)), col = "magenta")
lines(density(na.omit(macs2_narrowH1AllPeaks$Kurtosis)), col = "blue")
lines(density(na.omit(peakdeckH1AllPeaks$Kurtosis)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqH1AllNonPeaks$Kurtosis)), main="Distribution of Non-Peak Kurtosis", xlab="Kurtosis", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadH1AllNonPeaks$Kurtosis)), col = "magenta")
lines(density(na.omit(macs2_narrowH1AllNonPeaks$Kurtosis)), col = "blue")
lines(density(na.omit(peakdeckH1AllNonPeaks$Kurtosis)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```


Load all data.
```{r}
chroms = c(as.character(seq(1,22)), "x", "y")
chroms_non = c(as.character(c(5, 10)))
fseqA549StatList = vector("list", 24)
fseqA549NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\A549_fseq10_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  fseqA549StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\A549_fseq_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    fseqA549NonStatList[[ind]] = tempNonFrame
  }
}
fseqA549AllPeaks = do.call("rbind", fseqA549StatList[1:24])
fseqA549AllNonPeaks = do.call("rbind", fseqA549NonStatList[1:2])
```

```{r}
macs2_broadA549StatList = vector("list", 24)
macs2_broadA549NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\A549_macs2_broad_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_broadA549StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\A549_macs2_broad_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    macs2_broadA549NonStatList[[ind]] = tempNonFrame
  }
}
macs2_broadA549AllPeaks = do.call("rbind", macs2_broadA549StatList[1:24])
macs2_broadA549AllNonPeaks = do.call("rbind", macs2_broadA549NonStatList[1:2])
```

```{r}
macs2_narrowA549StatList = vector("list", 24)
macs2_narrowA549NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\A549_macs2_narrow_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_narrowA549StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\A549_macs2_narrow_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    macs2_narrowA549NonStatList[[ind]] = tempNonFrame
  }
}
macs2_narrowA549AllPeaks = do.call("rbind", macs2_narrowA549StatList[1:24])
macs2_narrowA549AllNonPeaks = do.call("rbind", macs2_narrowA549NonStatList[1:2])
```

```{r}
peakdeckA549StatList = vector("list", 24)
peakdeckA549NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\A549_peakdeck_csvs\\peakStatschr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  peakdeckA549StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\A549_peakdeck_non_csvs\\peakStatschr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    peakdeckA549NonStatList[[ind]] = tempNonFrame
  }
}
peakdeckA549AllPeaks = do.call("rbind", peakdeckA549StatList[1:24])
peakdeckA549AllNonPeaks = do.call("rbind", peakdeckA549NonStatList[1:2])
```
Look at histogram of each statistic (non-peak).
```{r}
plot(density(fseqA549AllPeaks$Size), main="Distribution of Peak Size", xlab="Peak Size (in increments of 50)", xlim = c(0,150), col = "green")
lines(density(macs2_broadA549AllPeaks$Size), col = "magenta")
lines(density(macs2_narrowA549AllPeaks$Size), col = "blue")
lines(density(peakdeckA549AllPeaks$Size), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqA549AllNonPeaks$Size), main="Distribution of Peak Size", xlab="Peak Size (in increments of 50)", xlim = c(0,50), col = "green")
lines(density(macs2_broadA549AllNonPeaks$Size), col = "magenta")
lines(density(macs2_narrowA549AllNonPeaks$Size), col = "blue")
lines(density(peakdeckA549AllNonPeaks$Size), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```
```{r}
plot(density(fseqA549AllPeaks$Min), main="Distribution of Peak Min", xlab="Peak Min", xlim = c(0,10), col = "green")
lines(density(macs2_broadA549AllPeaks$Min), col = "magenta")
lines(density(macs2_narrowA549AllPeaks$Min), col = "blue")
lines(density(peakdeckA549AllPeaks$Min), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqA549AllNonPeaks$Min), main="Distribution of Peak Size", xlab="Peak Min)", xlim = c(0,10), col = "green")
lines(density(macs2_broadA549AllNonPeaks$Min), col = "magenta")
lines(density(macs2_narrowA549AllNonPeaks$Min), col = "blue")
lines(density(peakdeckA549AllNonPeaks$Min), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(fseqA549AllPeaks$Max), main="Distribution of Peak Max", xlab="Peak Max", xlim = c(0,40), col = "green")
lines(density(macs2_broadA549AllPeaks$Max), col = "magenta")
lines(density(macs2_narrowA549AllPeaks$Max), col = "blue")
lines(density(peakdeckA549AllPeaks$Max), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqA549AllNonPeaks$Max), main="Distribution of Non-Peak Max", xlab="Peak Max)", xlim = c(0,40), col = "green")
lines(density(macs2_broadA549AllNonPeaks$Max), col = "magenta")
lines(density(macs2_narrowA549AllNonPeaks$Max), col = "blue")
lines(density(peakdeckA549AllNonPeaks$Max), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(fseqA549AllPeaks$Mean), main="Distribution of Peak Mean", xlab="Peak Mean", xlim = c(0,40), col = "green")
lines(density(macs2_broadA549AllPeaks$Mean), col = "magenta")
lines(density(macs2_narrowA549AllPeaks$Mean), col = "blue")
lines(density(peakdeckA549AllPeaks$Mean), col = "red")

plot(density(fseqA549AllNonPeaks$Mean), main="Distribution of Non-Peak Mean", xlab="Peak Mean)", xlim = c(0,40), col = "green")
lines(density(macs2_broadA549AllNonPeaks$Mean), col = "magenta")
lines(density(macs2_narrowA549AllNonPeaks$Mean), col = "blue")
lines(density(peakdeckA549AllNonPeaks$Mean), col = "red")
```

```{r}
plot(density(na.omit(fseqA549AllPeaks$Variance)), main="Distribution of Peak Variance", xlab="Peak Variance", xlim = c(0,40), col = "green")
lines(density(na.omit(macs2_broadA549AllPeaks$Variance)), col = "magenta")
lines(density(na.omit(macs2_narrowA549AllPeaks$Variance)), col = "blue")
lines(density(na.omit(peakdeckA549AllPeaks$Variance)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqA549AllNonPeaks$Variance)), main="Distribution of Non-Peak Variance", xlab="Peak Variance", xlim = c(0,40), col = "green")
lines(density(na.omit(macs2_broadA549AllNonPeaks$Variance)), col = "magenta")
lines(density(na.omit(macs2_narrowA549AllNonPeaks$Variance)), col = "blue")
lines(density(na.omit(peakdeckA549AllNonPeaks$Variance)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqA549AllPeaks$Skewness)), main="Distribution of Peak Skewness", xlab="Peak Skewness", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadA549AllPeaks$Skewness)), col = "magenta")
lines(density(na.omit(macs2_narrowA549AllPeaks$Skewness)), col = "blue")
lines(density(na.omit(peakdeckA549AllPeaks$Skewness)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqA549AllNonPeaks$Skewness)), main="Distribution of Non-Peak Skewness", xlab="Peak Skewness", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadA549AllNonPeaks$Skewness)), col = "magenta")
lines(density(na.omit(macs2_narrowA549AllNonPeaks$Skewness)), col = "blue")
lines(density(na.omit(peakdeckA549AllNonPeaks$Skewness)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqA549AllPeaks$Kurtosis)), main="Distribution of Peak Kurtosis", xlab="Peak Kurtosis", xlim = c(-5,15), col = "green")
lines(density(na.omit(macs2_broadA549AllPeaks$Kurtosis)), col = "magenta")
lines(density(na.omit(macs2_narrowA549AllPeaks$Kurtosis)), col = "blue")
lines(density(na.omit(peakdeckA549AllPeaks$Kurtosis)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqA549AllNonPeaks$Kurtosis)), main="Distribution of Non-Peak Kurtosis", xlab="Kurtosis", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadA549AllNonPeaks$Kurtosis)), col = "magenta")
lines(density(na.omit(macs2_narrowA549AllNonPeaks$Kurtosis)), col = "blue")
lines(density(na.omit(peakdeckA549AllNonPeaks$Kurtosis)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
chroms = c(as.character(seq(1,22)), "x", "y")
chroms_non = c(as.character(c(5, 10)))
fseqK562StatList = vector("list", 24)
fseqK562NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\K562_fseq10_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  fseqK562StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\K562_fseq_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    fseqK562NonStatList[[ind]] = tempNonFrame
  }
}
fseqK562AllPeaks = do.call("rbind", fseqK562StatList[1:24])
fseqK562AllNonPeaks = do.call("rbind", fseqK562NonStatList[1:2])
```

```{r}
macs2_broadK562StatList = vector("list", 24)
macs2_broadK562NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\K562_macs2_broad_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_broadK562StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\K562_macs2_broad_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    macs2_broadK562NonStatList[[ind]] = tempNonFrame
  }
}
macs2_broadK562AllPeaks = do.call("rbind", macs2_broadK562StatList[1:24])
macs2_broadK562AllNonPeaks = do.call("rbind", macs2_broadK562NonStatList[1:2])
```

```{r}
macs2_narrowK562StatList = vector("list", 24)
macs2_narrowK562NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\K562_macs2_narrow_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_narrowK562StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\K562_macs2_narrow_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    macs2_narrowK562NonStatList[[ind]] = tempNonFrame
  }
}
macs2_narrowK562AllPeaks = do.call("rbind", macs2_narrowK562StatList[1:24])
macs2_narrowK562AllNonPeaks = do.call("rbind", macs2_narrowK562NonStatList[1:2])
```

```{r}
peakdeckK562StatList = vector("list", 24)
peakdeckK562NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\K562_peakdeck_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  peakdeckK562StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\K562_peakdeck_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    peakdeckK562NonStatList[[ind]] = tempNonFrame
  }
}
peakdeckK562AllPeaks = do.call("rbind", peakdeckK562StatList[1:24])
peakdeckK562AllNonPeaks = do.call("rbind", peakdeckK562NonStatList[1:2])
```
Look at histogram of each statistic (non-peak).
```{r}
plot(density(fseqK562AllPeaks$Size), main="Distribution of Peak Size", xlab="Peak Size (in increments of 50)", xlim = c(0,150), col = "green")
lines(density(macs2_broadK562AllPeaks$Size), col = "magenta")
lines(density(macs2_narrowK562AllPeaks$Size), col = "blue")
lines(density(peakdeckK562AllPeaks$Size), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqK562AllNonPeaks$Size), main="Distribution of Peak Size", xlab="Peak Size (in increments of 50)", xlim = c(0,50), col = "green")
lines(density(macs2_broadK562AllNonPeaks$Size), col = "magenta")
lines(density(macs2_narrowK562AllNonPeaks$Size), col = "blue")
lines(density(peakdeckK562AllNonPeaks$Size), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(fseqK562AllPeaks$Min), main="Distribution of Peak Min", xlab="Peak Min", xlim = c(0,10), col = "green")
lines(density(macs2_broadK562AllPeaks$Min), col = "magenta")
lines(density(macs2_narrowK562AllPeaks$Min), col = "blue")
lines(density(peakdeckK562AllPeaks$Min), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqK562AllNonPeaks$Min), main="Distribution of Peak Size", xlab="Peak Min)", xlim = c(0,10), col = "green")
lines(density(macs2_broadK562AllNonPeaks$Min), col = "magenta")
lines(density(macs2_narrowK562AllNonPeaks$Min), col = "blue")
lines(density(peakdeckK562AllNonPeaks$Min), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(fseqK562AllPeaks$Max), main="Distribution of Peak Max", xlab="Peak Max", xlim = c(0,40), col = "green")
lines(density(macs2_broadK562AllPeaks$Max), col = "magenta")
lines(density(macs2_narrowK562AllPeaks$Max), col = "blue")
lines(density(peakdeckK562AllPeaks$Max), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqK562AllNonPeaks$Max), main="Distribution of Non-Peak Max", xlab="Peak Max)", xlim = c(0,40), col = "green")
lines(density(macs2_broadK562AllNonPeaks$Max), col = "magenta")
lines(density(macs2_narrowK562AllNonPeaks$Max), col = "blue")
lines(density(peakdeckK562AllNonPeaks$Max), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(fseqK562AllPeaks$Mean), main="Distribution of Peak Mean", xlab="Peak Mean", xlim = c(0,40), col = "green")
lines(density(macs2_broadK562AllPeaks$Mean), col = "magenta")
lines(density(macs2_narrowK562AllPeaks$Mean), col = "blue")
lines(density(peakdeckK562AllPeaks$Mean), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqK562AllNonPeaks$Mean), main="Distribution of Non-Peak Mean", xlab="Peak Mean)", xlim = c(0,40), col = "green")
lines(density(macs2_broadK562AllNonPeaks$Mean), col = "magenta")
lines(density(macs2_narrowK562AllNonPeaks$Mean), col = "blue")
lines(density(peakdeckK562AllNonPeaks$Mean), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqK562AllPeaks$Variance)), main="Distribution of Peak Variance", xlab="Peak Variance", xlim = c(0,40), col = "green")
lines(density(na.omit(macs2_broadK562AllPeaks$Variance)), col = "magenta")
lines(density(na.omit(macs2_narrowK562AllPeaks$Variance)), col = "blue")
lines(density(na.omit(peakdeckK562AllPeaks$Variance)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqK562AllNonPeaks$Variance)), main="Distribution of Non-Peak Variance", xlab="Peak Variance", xlim = c(0,40), col = "green")
lines(density(na.omit(macs2_broadK562AllNonPeaks$Variance)), col = "magenta")
lines(density(na.omit(macs2_narrowK562AllNonPeaks$Variance)), col = "blue")
lines(density(na.omit(peakdeckK562AllNonPeaks$Variance)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqK562AllPeaks$Skewness)), main="Distribution of Peak Skewness", xlab="Peak Skewness", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadK562AllPeaks$Skewness)), col = "magenta")
lines(density(na.omit(macs2_narrowK562AllPeaks$Skewness)), col = "blue")
lines(density(na.omit(peakdeckK562AllPeaks$Skewness)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqK562AllNonPeaks$Skewness)), main="Distribution of Non-Peak Skewness", xlab="Peak Skewness", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadK562AllNonPeaks$Skewness)), col = "magenta")
lines(density(na.omit(macs2_narrowK562AllNonPeaks$Skewness)), col = "blue")
lines(density(na.omit(peakdeckK562AllNonPeaks$Skewness)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqK562AllPeaks$Kurtosis)), main="Distribution of Peak Kurtosis", xlab="Peak Kurtosis", xlim = c(-5,15), col = "green")
lines(density(na.omit(macs2_broadK562AllPeaks$Kurtosis)), col = "magenta")
lines(density(na.omit(macs2_narrowH1AllPeaks$Kurtosis)), col = "blue")
lines(density(na.omit(peakdeckH1AllPeaks$Kurtosis)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqK562AllNonPeaks$Kurtosis)), main="Distribution of Non-Peak Kurtosis", xlab="Kurtosis", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadK562AllNonPeaks$Kurtosis)), col = "magenta")
lines(density(na.omit(macs2_narrowK562AllNonPeaks$Kurtosis)), col = "blue")
lines(density(na.omit(peakdeckK562AllNonPeaks$Kurtosis)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```
```{r}
chroms = c(as.character(seq(1,22)), "x", "y")
chroms_non = c(as.character(c(5, 10)))
fseqIMR90StatList = vector("list", 24)
fseqIMR90NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\IMR90_fseq10_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  fseqIMR90StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\IMR90_fseq_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    fseqIMR90NonStatList[[ind]] = tempNonFrame
  }
}
fseqIMR90AllPeaks = do.call("rbind", fseqIMR90StatList[1:24])
fseqIMR90AllNonPeaks = do.call("rbind", fseqIMR90NonStatList[1:2])
```

```{r}
macs2_broadIMR90StatList = vector("list", 24)
macs2_broadIMR90NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\IMR90_macs2_broad_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_broadIMR90StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\IMR90_macs2_broad_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    macs2_broadIMR90NonStatList[[ind]] = tempNonFrame
  }
}
macs2_broadIMR90AllPeaks = do.call("rbind", macs2_broadIMR90StatList[1:24])
macs2_broadIMR90AllNonPeaks = do.call("rbind", macs2_broadIMR90NonStatList[1:2])
```

```{r}
macs2_narrowIMR90StatList = vector("list", 24)
macs2_narrowIMR90NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\IMR90_macs2_narrow_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_narrowIMR90StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\IMR90_macs2_narrow_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    macs2_narrowIMR90NonStatList[[ind]] = tempNonFrame
  }
}
macs2_narrowIMR90AllPeaks = do.call("rbind", macs2_narrowIMR90StatList[1:24])
macs2_narrowIMR90AllNonPeaks = do.call("rbind", macs2_narrowIMR90NonStatList[1:2])
```

```{r}
peakdeckIMR90StatList = vector("list", 24)
peakdeckIMR90NonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\IMR90_peakdeck_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  peakdeckIMR90StatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\IMR90_peakdeck_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    peakdeckIMR90NonStatList[[ind]] = tempNonFrame
  }
}
peakdeckIMR90AllPeaks = do.call("rbind", peakdeckIMR90StatList[1:24])
peakdeckIMR90AllNonPeaks = do.call("rbind", peakdeckIMR90NonStatList[1:2])
```
Look at histogram of each statistic (non-peak).
```{r}
plot(density(fseqIMR90AllPeaks$Size), main="Distribution of Peak Size", xlab="Peak Size (in increments of 50)", xlim = c(0,150), col = "green")
lines(density(macs2_broadIMR90AllPeaks$Size), col = "magenta")
lines(density(macs2_narrowIMR90AllPeaks$Size), col = "blue")
lines(density(peakdeckIMR90AllPeaks$Size), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqIMR90AllNonPeaks$Size), main="Distribution of Peak Size", xlab="Peak Size (in increments of 50)", xlim = c(0,50), col = "green")
lines(density(macs2_broadIMR90AllNonPeaks$Size), col = "magenta")
lines(density(macs2_narrowIMR90AllNonPeaks$Size), col = "blue")
lines(density(peakdeckIMR90AllNonPeaks$Size), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```
```{r}
plot(density(fseqIMR90AllPeaks$Min), main="Distribution of Peak Min", xlab="Peak Min", xlim = c(0,10), col = "green")
lines(density(macs2_broadIMR90AllPeaks$Min), col = "magenta")
lines(density(macs2_narrowIMR90AllPeaks$Min), col = "blue")
lines(density(peakdeckIMR90AllPeaks$Min), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqIMR90AllNonPeaks$Min), main="Distribution of Peak Size", xlab="Peak Min)", xlim = c(0,10), col = "green")
lines(density(macs2_broadIMR90AllNonPeaks$Min), col = "magenta")
lines(density(macs2_narrowIMR90AllNonPeaks$Min), col = "blue")
lines(density(peakdeckIMR90AllNonPeaks$Min), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(fseqIMR90AllPeaks$Max), main="Distribution of Peak Max", xlab="Peak Max", xlim = c(0,40), col = "green")
lines(density(macs2_broadIMR90AllPeaks$Max), col = "magenta")
lines(density(macs2_narrowIMR90AllPeaks$Max), col = "blue")
lines(density(peakdeckIMR90AllPeaks$Max), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqIMR90AllNonPeaks$Max), main="Distribution of Non-Peak Max", xlab="Peak Max)", xlim = c(0,40), col = "green")
lines(density(macs2_broadIMR90AllNonPeaks$Max), col = "magenta")
lines(density(macs2_narrowIMR90AllNonPeaks$Max), col = "blue")
lines(density(peakdeckIMR90AllNonPeaks$Max), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(fseqIMR90AllPeaks$Mean), main="Distribution of Peak Mean", xlab="Peak Mean", xlim = c(0,40), col = "green")
lines(density(macs2_broadIMR90AllPeaks$Mean), col = "magenta")
lines(density(macs2_narrowIMR90AllPeaks$Mean), col = "blue")
lines(density(peakdeckIMR90AllPeaks$Mean), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(fseqIMR90AllNonPeaks$Mean), main="Distribution of Non-Peak Mean", xlab="Peak Mean)", xlim = c(0,40), col = "green")
lines(density(macs2_broadIMR90AllNonPeaks$Mean), col = "magenta")
lines(density(macs2_narrowIMR90AllNonPeaks$Mean), col = "blue")
lines(density(peakdeckIMR90AllNonPeaks$Mean), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqIMR90AllPeaks$Variance)), main="Distribution of Peak Variance", xlab="Peak Variance", xlim = c(0,40), col = "green")
lines(density(na.omit(macs2_broadIMR90AllPeaks$Variance)), col = "magenta")
lines(density(na.omit(macs2_narrowIMR90AllPeaks$Variance)), col = "blue")
lines(density(na.omit(peakdeckIMR90AllPeaks$Variance)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqIMR90AllNonPeaks$Variance)), main="Distribution of Non-Peak Variance", xlab="Peak Variance", xlim = c(0,40), col = "green")
lines(density(na.omit(macs2_broadIMR90AllNonPeaks$Variance)), col = "magenta")
lines(density(na.omit(macs2_narrowIMR90AllNonPeaks$Variance)), col = "blue")
lines
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqIMR90AllPeaks$Skewness)), main="Distribution of Peak Skewness", xlab="Peak Skewness", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadIMR90AllPeaks$Skewness)), col = "magenta")
lines(density(na.omit(macs2_narrowIMR90AllPeaks$Skewness)), col = "blue")
lines(density(na.omit(peakdeckIMR90AllPeaks$Skewness)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqIMR90AllNonPeaks$Skewness)), main="Distribution of Non-Peak Skewness", xlab="Peak Skewness", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadIMR90AllNonPeaks$Skewness)), col = "magenta")
lines(density(na.omit(macs2_narrowIMR90AllNonPeaks$Skewness)), col = "blue")
lines(density(na.omit(peakdeckIMR90AllNonPeaks$Skewness)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqIMR90AllPeaks$Kurtosis)), main="Distribution of Peak Kurtosis", xlab="Peak Kurtosis", xlim = c(-5,15), col = "green")
lines(density(na.omit(macs2_broadIMR90AllPeaks$Kurtosis)), col = "magenta")
lines(density(na.omit(macs2_narrowIMR90AllPeaks$Kurtosis)), col = "blue")
lines(density(na.omit(peakdeckIMR90AllPeaks$Kurtosis)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqH1AllNonPeaks$Kurtosis)), main="Distribution of Non-Peak Kurtosis", xlab="Kurtosis", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadIMR90AllNonPeaks$Kurtosis)), col = "magenta")
lines(density(na.omit(macs2_narrowIMR90AllNonPeaks$Kurtosis)), col = "blue")
lines(density(na.omit(peakdeckIMR90AllNonPeaks$Kurtosis)), col = "red")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```
```{r}
chroms = c(as.character(seq(1,22)), "x", "y")
chroms_non = c(as.character(c(5, 10)))
fseqBrainStatList = vector("list", 24)
fseqBrainNonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\Brain_fseq10_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  fseqBrainStatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\Brain_fseq_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    fseqBrainNonStatList[[ind]] = tempNonFrame
  }
}
fseqBrainAllPeaks = do.call("rbind", fseqBrainStatList[1:24])
fseqBrainAllNonPeaks = do.call("rbind", fseqBrainNonStatList[1:2])
```

```{r}
macs2_broadBrainStatList = vector("list", 24)
macs2_broadBrainNonStatList = vector("list", 2)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\Brain_macs2_broad_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_broadBrainStatList[[i]] = tempFrame
  ind = match(i, chroms_non)
  if(!(is.na(ind))){
    tempNonFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\Brain_macs2_broad_non_csvs\\chr", chroms_non[[ind]], ".csv", sep = ""))
    names(tempNonFrame) = names(tempFrame)
    macs2_broadBrainNonStatList[[ind]] = tempNonFrame
  }
}
macs2_broadBrainAllPeaks = do.call("rbind", macs2_broadBrainStatList[1:24])
macs2_broadBrainAllNonPeaks = do.call("rbind", macs2_broadBrainNonStatList[1:2])
```

```{r}
macs2_narrowBrainStatList = vector("list", 24)
for(i in 1:length(chroms)){
  tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\Brain_macs2_narrow_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_narrowBrainStatList[[i]] = tempFrame
  ind = match(i, chroms_non)
}
macs2_narrowBrainAllPeaks = do.call("rbind", macs2_narrowBrainStatList[1:24])
```

```{r}
peakdeckBrainStatList = vector("list", 24)
for(i in 1:length(chroms)){
  frameName = paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\Brain_peakdeck_csvs\\chr", chroms[i], ".csv", sep = "")
  tempFrame = data.frame()
  if (!file.size(frameName) == 0)
    tempFrame = read.csv(paste("C:\\Users\\tarae\\OneDrive\\Documents\\PhD\\Research\\PeakCalling\\Brain_peakdeck_csvs\\chr", chroms[i], ".csv", sep = ""))
  names(tempFrame) = c("Size", "Min", "Max", "Mean", "Variance", "Skewness", "Kurtosis")
  macs2_narrowBrainStatList[[i]] = tempFrame
  ind = match(i, chroms_non)
}
peakdeckBrainAllPeaks = do.call("rbind", peakdeckBrainStatList[1:24])
```
Look at histogram of each statistic (non-peak).
```{r}
plot(density(fseqBrainAllPeaks$Size), main="Distribution of Peak Size", xlab="Peak Size (in increments of 50)", xlim = c(0,150), col = "green")
lines(density(macs2_broadBrainAllPeaks$Size), col = "magenta")
lines(density(macs2_narrowBrainAllPeaks$Size), col = "blue")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow"), col= c("green", "magenta", "blue"), lwd = 2)

plot(density(fseqBrainAllNonPeaks$Size), main="Distribution of Peak Size", xlab="Peak Size (in increments of 50)", xlim = c(0,50), col = "green")
lines(density(macs2_broadBrainAllNonPeaks$Size), col = "magenta")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow"), col= c("green", "magenta", "blue"), lwd = 2)
```
```{r}
plot(density(fseqBrainAllPeaks$Min), main="Distribution of Peak Min", xlab="Peak Min", xlim = c(0,10), col = "green")
lines(density(macs2_broadBrainAllPeaks$Min), col = "magenta")
lines(density(macs2_narrowBrainAllPeaks$Min), col = "blue")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow"), col= c("green", "magenta", "blue"), lwd = 2)

plot(density(fseqBrainAllNonPeaks$Min), main="Distribution of Peak Size", xlab="Peak Min)", xlim = c(0,10), col = "green")
lines(density(macs2_broadBrainAllNonPeaks$Min), col = "magenta")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad"), col= c("green", "magenta"), lwd = 2)
```

```{r}
plot(density(fseqBrainAllPeaks$Max), main="Distribution of Peak Max", xlab="Peak Max", xlim = c(0,40), col = "green")
lines(density(macs2_broadBrainAllPeaks$Max), col = "magenta")
lines(density(macs2_narrowBrainAllPeaks$Max), col = "blue")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow"), col= c("green", "magenta", "blue"), lwd = 2)

plot(density(fseqBrainAllNonPeaks$Max), main="Distribution of Non-Peak Max", xlab="Peak Max)", xlim = c(0,40), col = "green")
lines(density(macs2_broadBrainAllNonPeaks$Max), col = "magenta")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad"), col= c("green", "magenta"), lwd = 2)
```

```{r}
plot(density(fseqBrainAllPeaks$Mean), main="Distribution of Peak Mean", xlab="Peak Mean", xlim = c(0,40), col = "green")
lines(density(macs2_broadBrainAllPeaks$Mean), col = "magenta")
lines(density(macs2_narrowBrainAllPeaks$Mean), col = "blue")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow"), col= c("green", "magenta", "blue"), lwd = 2)

plot(density(fseqBrainAllNonPeaks$Mean), main="Distribution of Non-Peak Mean", xlab="Peak Mean)", xlim = c(0,40), col = "green")
lines(density(macs2_broadBrainAllNonPeaks$Mean), col = "magenta")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad"), col= c("green", "magenta"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqBrainAllPeaks$Variance)), main="Distribution of Peak Variance", xlab="Peak Variance", xlim = c(0,40), col = "green")
lines(density(na.omit(macs2_broadBrainAllPeaks$Variance)), col = "magenta")
lines(density(na.omit(macs2_narrowBrainAllPeaks$Variance)), col = "blue")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow"), col= c("green", "magenta", "blue"), lwd = 2)

plot(density(na.omit(fseqBrainAllNonPeaks$Variance)), main="Distribution of Non-Peak Variance", xlab="Peak Variance", xlim = c(0,40), col = "green")
lines(density(na.omit(macs2_broadBrainAllNonPeaks$Variance)), col = "magenta")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad"), col= c("green", "magenta"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqBrainAllPeaks$Skewness)), main="Distribution of Peak Skewness", xlab="Peak Skewness", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadBrainAllPeaks$Skewness)), col = "magenta")
lines(density(na.omit(macs2_narrowBrainAllPeaks$Skewness)), col = "blue")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow"), col= c("green", "magenta", "blue"), lwd = 2)

plot(density(na.omit(fseqBrainAllNonPeaks$Skewness)), main="Distribution of Non-Peak Skewness", xlab="Peak Skewness", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadBrainAllNonPeaks$Skewness)), col = "magenta")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad"), col= c("green", "magenta"), lwd = 2)
```

```{r}
plot(density(na.omit(fseqBrainAllPeaks$Kurtosis)), main="Distribution of Peak Kurtosis", xlab="Peak Kurtosis", xlim = c(-5,15), col = "green")
lines(density(na.omit(macs2_broadBrainAllPeaks$Kurtosis)), col = "magenta")
lines(density(na.omit(macs2_narrowBrainAllPeaks$Kurtosis)), col = "blue")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)

plot(density(na.omit(fseqBrainAllNonPeaks$Kurtosis)), main="Distribution of Non-Peak Kurtosis", xlab="Kurtosis", xlim = c(-5,5), col = "green")
lines(density(na.omit(macs2_broadBrainAllNonPeaks$Kurtosis)), col = "magenta")
legend(x= "topright", y=0.92, legend=c("F-Seq", "MACS2 Broad", "MACS2 Narrow", "PeaKDEck"), col= c("green", "magenta", "blue", "red"), lwd = 2)
```